let bbbMapData = 
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "bbb_airports" } },
"features": [
{ "type": "Feature", "properties": { "name":" Wright-Patterson Air Force Base, OH, USA "}, "geometry": { "type": "Point", "coordinates": [  -84.067406 ,  39.819527 ] } },
{ "type": "Feature", "properties": { "name":" John F. Kennedy International Airport, NY, USA "}, "geometry": { "type": "Point", "coordinates": [  -73.780968 ,  40.641766 ] } },
{ "type": "Feature", "properties": { "name":" Charlotte Douglas International Airport, Charlotte, NC, USA "}, "geometry": { "type": "Point", "coordinates": [  -80.943054 ,  35.21389 ] } },
{ "type": "Feature", "properties": { "name":" O’Hare International Airport, Chicago, IL, USA "}, "geometry": { "type": "Point", "coordinates": [  -87.904724 ,  41.978611 ] } },
{ "type": "Feature", "properties": { "name":" Tucson International Airport, Tuscon, Arizona, US "}, "geometry": { "type": "Point", "coordinates": [  -110.941109 ,  32.116112 ] } },
{ "type": "Feature", "properties": { "name":" Candy Kitchen Ranch Airport, Ramah, NM, USA "}, "geometry": { "type": "Point", "coordinates": [  -108.514519 ,  34.903271 ] } },
{ "type": "Feature", "properties": { "name":" Canandaigua Airport - KIUA, Canandaigua, NY, USA "}, "geometry": { "type": "Point", "coordinates": [  -77.31897 ,  42.907768 ] } },
{ "type": "Feature", "properties": { "name":" Asheville Regional Airport, Fletcher, NC, USA "}, "geometry": { "type": "Point", "coordinates": [  -82.541298 ,  35.436077 ] } },
{ "type": "Feature", "properties": { "name":" Dallas Love Field Airport, Dallas, TX, USA "}, "geometry": { "type": "Point", "coordinates": [  -96.851349 ,  32.848152 ] } },
{ "type": "Feature", "properties": { "name":" Fly Barts, East Moriches, NY, the USA "}, "geometry": { "type": "Point", "coordinates": [  -72.748634 ,  40.822773 ] } },
{ "type": "Feature", "properties": { "name":" Tampa International Airport, Tampa, FL, USA "}, "geometry": { "type": "Point", "coordinates": [  -82.539337 ,  27.979168 ] } },
{ "type": "Feature", "properties": { "name":" Kotlik Airport (KOT), Kotlik, AK, USA "}, "geometry": { "type": "Point", "coordinates": [  -163.527863 ,  63.035789 ] } },
{ "type": "Feature", "properties": { "name":" Michael Army Airfield (DPG), Utah, USA "}, "geometry": { "type": "Point", "coordinates": [  -112.937469 ,  40.199387 ] } },
{ "type": "Feature", "properties": { "name":" Emerald Coast Aviation, Crestview, FL, USA "}, "geometry": { "type": "Point", "coordinates": [  -86.524994 ,  30.781055 ] } },
{ "type": "Feature", "properties": { "name":" Preston Smith International Airport, Lubbock, TX, USA "}, "geometry": { "type": "Point", "coordinates": [  -101.821861 ,  33.656384 ] } },
{ "type": "Feature", "properties": { "name":" Eagle Landing Airport LZ, Avinger, TX, USA "}, "geometry": { "type": "Point", "coordinates": [  -94.599251 ,  32.886677 ] } },
{ "type": "Feature", "properties": { "name":" Greater Rochester International Airport, Rochester, NY, USA "}, "geometry": { "type": "Point", "coordinates": [  -77.665474 ,  43.128002 ] } },
{ "type": "Feature", "properties": { "name":" Warrenton-Fauquier Airport (KHWY), Midland, VA, USA "}, "geometry": { "type": "Point", "coordinates": [  -77.711441 ,  38.592724 ] } },
{ "type": "Feature", "properties": { "name":" San Diego International Airport (SAN), San Diego, CA, USA "}, "geometry": { "type": "Point", "coordinates": [  -117.197624 ,  32.73177 ] } },
{ "type": "Feature", "properties": { "name":" Mc Donald Field, Marshville, NC, USA "}, "geometry": { "type": "Point", "coordinates": [  -80.409195 ,  35.053238 ] } },
{ "type": "Feature", "properties": { "name":" Nashville International Airport (BNA), Nashville, TN, USA "}, "geometry": { "type": "Point", "coordinates": [  -86.668823 ,  36.131687 ] } },
{ "type": "Feature", "properties": { "name":" Lackland AFB, San Antonio, TX, USA "}, "geometry": { "type": "Point", "coordinates": [  -98.618645 ,  29.384344 ] } },
{ "type": "Feature", "properties": { "name":" Seattle-Tacoma International Airport, WA, USA "}, "geometry": { "type": "Point", "coordinates": [  -122.301659 ,  47.443546 ] } },
{ "type": "Feature", "properties": { "name":" McGhee Tyson Airport (TYS), Alcoa, TN, USA "}, "geometry": { "type": "Point", "coordinates": [  -83.989815 ,  35.805813 ] } },
{ "type": "Feature", "properties": { "name":" Kenai Municipal Airport, Kenai, AK, USA "}, "geometry": { "type": "Point", "coordinates": [  -151.246719 ,  60.567402 ] } },
{ "type": "Feature", "properties": { "name":" Fort Gordon, Augusta, GA, USA "}, "geometry": { "type": "Point", "coordinates": [  -82.152374 ,  33.420696 ] } },
{ "type": "Feature", "properties": { "name":" Mineta San José International Airport (SJC), San Jose, CA, USA "}, "geometry": { "type": "Point", "coordinates": [  -121.92894 ,  37.363949 ] } },
{ "type": "Feature", "properties": { "name":" Hartsfield-Jackson Atlanta International Airport, Atlanta, GA, USA "}, "geometry": { "type": "Point", "coordinates": [  -84.419853 ,  33.640411 ] } },
{ "type": "Feature", "properties": { "name":" Santa Fe Municipal Airport (SAF), Santa Fe, NM, USA "}, "geometry": { "type": "Point", "coordinates": [  -106.088333 ,  35.6175 ] } },
{ "type": "Feature", "properties": { "name":" Delta County Airport (ESC), Escanaba, MI, USA "}, "geometry": { "type": "Point", "coordinates": [  -87.09407 ,  45.719906 ] } },
{ "type": "Feature", "properties": { "name":" Cincinnati/Northern Kentucky International Airport (CVG), Hebron, KY, USA "}, "geometry": { "type": "Point", "coordinates": [  -84.663017 ,  39.053276 ] } },
{ "type": "Feature", "properties": { "name":" San Diego International Airport (SAN), San Diego, CA, USA "}, "geometry": { "type": "Point", "coordinates": [  -117.196053 ,  32.732346 ] } },
{ "type": "Feature", "properties": { "name":" Falcon Field Airport, Mesa, AZ, USA "}, "geometry": { "type": "Point", "coordinates": [  -111.727386 ,  33.457439 ] } },
{ "type": "Feature", "properties": { "name":" John Wayne Airport (SNA), CA, USA "}, "geometry": { "type": "Point", "coordinates": [  -117.862869 ,  33.678925 ] } },
{ "type": "Feature", "properties": { "name":" San Francisco International Airport (SFO), USA "}, "geometry": { "type": "Point", "coordinates": [  -122.389977 ,  37.615223 ] } },
{ "type": "Feature", "properties": { "name":" Hunter Army Airfield, Savannah, GA, USA "}, "geometry": { "type": "Point", "coordinates": [  -81.143127 ,  32.015644 ] } },
{ "type": "Feature", "properties": { "name":" Los Angeles International Airport, USA "}, "geometry": { "type": "Point", "coordinates": [  -118.410042 ,  33.942791 ] } },
{ "type": "Feature", "properties": { "name":" Travis Air Force Base, Fairfield, USA "}, "geometry": { "type": "Point", "coordinates": [  -121.939857 ,  38.272118 ] } },
{ "type": "Feature", "properties": { "name":" North Las Vegas Airport (VGT), Las Vegas, USA "}, "geometry": { "type": "Point", "coordinates": [  -115.194572 ,  36.213257 ] } },
{ "type": "Feature", "properties": { "name":" Northern Lights Airport, Alburgh, VT, USA "}, "geometry": { "type": "Point", "coordinates": [  -73.286491 ,  44.871201 ] } },
{ "type": "Feature", "properties": { "name":" McCarran International Airport (LAS), Las Vegas, NV, USA "}, "geometry": { "type": "Point", "coordinates": [  -115.153969 ,  36.08601 ] } },
{ "type": "Feature", "properties": { "name":" Denver International Airport, CO, USA "}, "geometry": { "type": "Point", "coordinates": [  -104.673828 ,  39.849312 ] } },
{ "type": "Feature", "properties": { "name":" Pocatello Regional Airport, Pocatello, ID, USA "}, "geometry": { "type": "Point", "coordinates": [  -112.59304 ,  42.915703 ] } },
{ "type": "Feature", "properties": { "name":" Borrego Valley Airport (BXS), Borrego Springs, CA, USA "}, "geometry": { "type": "Point", "coordinates": [  -116.321014 ,  33.257923 ] } },
{ "type": "Feature", "properties": { "name":" Hatbox Field Airport, Muskogee, OK, USA "}, "geometry": { "type": "Point", "coordinates": [  -95.412529 ,  35.748463 ] } },
{ "type": "Feature", "properties": { "name":" Unalakleet Airport (UNK), Unalakleet, AK, USA "}, "geometry": { "type": "Point", "coordinates": [  -160.799927 ,  63.889515 ] } },
{ "type": "Feature", "properties": { "name":" Boone County Regional Airport (HRO), Harrison, AR, USA "}, "geometry": { "type": "Point", "coordinates": [  -93.154961 ,  36.264206 ] } },
{ "type": "Feature", "properties": { "name":" St George Municipal Airport (SGU), St. George, UT, USA "}, "geometry": { "type": "Point", "coordinates": [  -113.508987 ,  37.030792 ] } },
{ "type": "Feature", "properties": { "name":" General Mitchell International Airport (MKE), Milwaukee, WI, USA "}, "geometry": { "type": "Point", "coordinates": [  -87.900414 ,  42.94989 ] } },
{ "type": "Feature", "properties": { "name":" Logan International Airport (BOS), Boston, MA, USA "}, "geometry": { "type": "Point", "coordinates": [  -71.022362 ,  42.366978 ] } },
{ "type": "Feature", "properties": { "name":" Naec Airport, Jackson, NJ, USA "}, "geometry": { "type": "Point", "coordinates": [  -74.338257 ,  40.032608 ] } },
{ "type": "Feature", "properties": { "name":" Memphis International Airport, TN, USA "}, "geometry": { "type": "Point", "coordinates": [  -89.981873 ,  35.040031 ] } },
{ "type": "Feature", "properties": { "name":" Cape Girardeau Regional Airport, MO, USA "}, "geometry": { "type": "Point", "coordinates": [  -89.569305 ,  37.225136 ] } },
{ "type": "Feature", "properties": { "name":" Dallas/Fort Worth International Airport, TX, USA "}, "geometry": { "type": "Point", "coordinates": [  -97.040443 ,  32.89748 ] } },
{ "type": "Feature", "properties": { "name":" Little Rock AFB, Jacksonville, AR, USA "}, "geometry": { "type": "Point", "coordinates": [  -92.142914 ,  34.914547 ] } },
{ "type": "Feature", "properties": { "name":" Spruce Creek Airport, FL, USA "}, "geometry": { "type": "Point", "coordinates": [  -81.046669 ,  29.080168 ] } },
{ "type": "Feature", "properties": { "name":" Gwinnett County Airport, GA, USA "}, "geometry": { "type": "Point", "coordinates": [  -83.963097 ,  33.975777 ] } }
]
}

